/*
 * location: NodeJS_Template_Repository/app.js
 * description: This is the server file that starts the entire NodeJS server. Without this file, the server
 * 							does not work at all, which is why it is in the home directory and not in the /src directory. It uses the
 * 							"express" package to create the app and start it. It sets the environment using the arguments passed on the
 * 							command line, sets the routes, sets the port, sets the app engine as Handlebars, and initializes the engine.
 * 							Additionally, it configures middleware for parsing request bodies and serving static files, and includes error
 * 							handling and logging using custom utilities.
 * installation: npm install
 * usage: npm run example
 */

const express = require("express");
const path = require("path");
const exphbs = require("express-handlebars");
const bodyParser = require("body-parser");

// create the app and configure the .env to choose a file based on the CLI input at time of run
const app = express();
require("dotenv").config({
	path: path.join(__dirname, `config/.env.${process.argv[2]}`),
});

// import the route file that holds all of the custom routes
const { total_routes } = require(path.join(__dirname, "/src/routes/index"));
// set the port based on the .env
const port = process.env.PORT || 8080;
// import the winston logger utility
const { logger } = require(path.join(__dirname, "/src/utils/winston_helper"));
// import the axios api requester utility
const requester = require(path.join(__dirname, "/src/utils/axios_helper"));

// set the engine and handlebars and set the layouts directory and default layout file name
app.engine(
	"hbs",
	exphbs.engine({
		extname: ".hbs",
		defaultLayout: "default",
		layoutsDir: path.join(__dirname, "/public/pages/layouts"),
		helpers: {
			eq: function (a, b) {
				return a === b;
			},
			ne: function (a, b) {
				return a !== b;
			},
			lt: function (a, b) {
				return a < b;
			},
			gt: function (a, b) {
				return a > b;
			},
			and: function (a, b) {
				return a && b;
			},
			or: function (a, b) {
				return a || b;
			},
		},
	})
);

// set the handlebars view engine and views directory
app.set("view engine", "hbs");
app.set("views", path.join(__dirname, "/public/pages/views"));

// set body-parser
app.use(bodyParser.urlencoded({ extended: true }));
// set the static files to be shown to clients as the public directory
app.use(express.static(path.join(__dirname, "/public")));
// actually use the routes previously imported
app.use("/", total_routes);

// small endpoint that catches any errors when connecting to the server in some manner
app.use((err, req, res, next) => {
	logger.error(err.stack);
	res.status(500).send("Something went wrong!");
});

// server is started by listening on the previously defined port
const server = app.listen(port, async () => {
	// runtime log to show that the server is running
	logger.debug(`Success! Server is listening at ${process.env.HOST}:${port}`);

	// log and test for where the true server logs go
	logger.debug(
		"To see the Winston logging package in effect, go to ./src/logs/ to see the new log generated by this code: logger.info('Testing Winston!')"
	);
	logger.info("Testing Winston!");

	logger.debug(
		"To see how an error is logged with Winston, check the same log file specified above for the output from a failed get request using the code from ./src/utils/axios_helper.js"
	);

	// run a quick get request to a guaranteed error
	var response = await requester.get_request("http://127.0.0:8080/example", {
		accept: "application/json",
	});

	// error checking for the response - this can be used as an example for how to debug the response from the requester
	if (response.success) {
		logger.debug("something insane has occurred");
	} else {
		logger.error(`Test Failed - ${response.data} with config: ${JSON.stringify(response.config)}`);
	}

	// log for example endpoint
	logger.debug(
		"To test the custom endpoint setup, simply navigate in a browser to the address listed above plus '/example' or ping with Postman!"
	);

	// test and log for the custom example endpoint
	response = await requester.get_request("http://127.0.0.1:8080/example", {
		accept: "application/json",
	});

	// error checking for the response - this can be used as an example for how to debug the response from the requester
	if (response.success) {
		logger.debug(
			`Test Succeeded - ${response.data} with config: ${JSON.stringify(response.config)}`
		);
	} else {
		logger.debug(`Test Failed - ${response.data} with config: ${JSON.stringify(response.config)}`);
	}
});
